### ISSUE TITLE
npm安装的包没有编译 vite运行报错

### ISSUE THREAD

**Issue by EvanYung** [vingogo/vin-ui#4]
![image](https://user-images.githubusercontent.com/20455032/228117722-ecb32eef-1f8d-4c46-a55f-32114b7d0cf3.png)

**Comment by Alvin-LM** [comment]
> ![image](https://user-images.githubusercontent.com/20455032/228117722-ecb32eef-1f8d-4c46-a55f-32114b7d0cf3.png)

这个是通过 npm link 执行的吗，这个结构的包还没有发布到 npm，建议先用 easycom
