### ISSUE TITLE
uniapp 插件市场下载，HBuilderX 编辑器运行还需要写代码备注css预处理器吗？

### ISSUE THREAD

**Issue by dong-lufei** [vingogo/vin-ui#7]
uniapp 插件市场下载安装的方式，HBuilderX 编辑器创建的项目并运行代码时自动提示安装 "sass/scss 编译" 插件后，还需要配置 sass/scss 吗？

https://vingogo.cn/docs/guide/official-theme.html

是不是不需要再配置 vite.config.js、vite.config.ts 或 webpack 了呀（感觉这些文件不存在都可以）？

**Comment by Alvin-LM** [comment]
>  

是的，不需要再配置了，如果习惯用 HBuilderX 的话可以直接用 uniapp 插件市场导入示例项目的方式：https://ext.dcloud.net.cn/plugin?id=11187

但是更推荐用 cli 的方式运行

样式如果引入的是 scss 文件的话，安装 "sass/scss 编译" 插件还是需要的
